// This file was generated by Mendix Modeler 6.10.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package twofactorauth.proxies.constants;

import com.mendix.core.Core;

public class Constants
{
	// These are the constants for the TwoFactorAuth module

	public static boolean getMagicLinkEnabled()
	{
		return (java.lang.Boolean)Core.getConfiguration().getConstantValue("TwoFactorAuth.MagicLinkEnabled");
	}

	public static boolean getTwoFactorEnabled()
	{
		return (java.lang.Boolean)Core.getConfiguration().getConstantValue("TwoFactorAuth.TwoFactorEnabled");
	}
}