// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package twofactorauth.proxies;

public class MagicLink
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject magicLinkMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "TwoFactorAuth.MagicLink";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		MagicGUID("MagicGUID"),
		MagicLink_Account("TwoFactorAuth.MagicLink_Account");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public MagicLink(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "TwoFactorAuth.MagicLink"));
	}

	protected MagicLink(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject magicLinkMendixObject)
	{
		if (magicLinkMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("TwoFactorAuth.MagicLink", magicLinkMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a TwoFactorAuth.MagicLink");

		this.magicLinkMendixObject = magicLinkMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'MagicLink.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static twofactorauth.proxies.MagicLink initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return twofactorauth.proxies.MagicLink.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.getSudoContext() can be used to obtain sudo access).
	 */
	public static twofactorauth.proxies.MagicLink initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new twofactorauth.proxies.MagicLink(context, mendixObject);
	}

	public static twofactorauth.proxies.MagicLink load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return twofactorauth.proxies.MagicLink.initialize(context, mendixObject);
	}

	public static java.util.List<twofactorauth.proxies.MagicLink> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<twofactorauth.proxies.MagicLink> result = new java.util.ArrayList<twofactorauth.proxies.MagicLink>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//TwoFactorAuth.MagicLink" + xpathConstraint))
			result.add(twofactorauth.proxies.MagicLink.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of MagicGUID
	 */
	public final java.lang.String getMagicGUID()
	{
		return getMagicGUID(getContext());
	}

	/**
	 * @param context
	 * @return value of MagicGUID
	 */
	public final java.lang.String getMagicGUID(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.MagicGUID.toString());
	}

	/**
	 * Set value of MagicGUID
	 * @param magicguid
	 */
	public final void setMagicGUID(java.lang.String magicguid)
	{
		setMagicGUID(getContext(), magicguid);
	}

	/**
	 * Set value of MagicGUID
	 * @param context
	 * @param magicguid
	 */
	public final void setMagicGUID(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String magicguid)
	{
		getMendixObject().setValue(context, MemberNames.MagicGUID.toString(), magicguid);
	}

	/**
	 * @return value of MagicLink_Account
	 */
	public final administration.proxies.Account getMagicLink_Account() throws com.mendix.core.CoreException
	{
		return getMagicLink_Account(getContext());
	}

	/**
	 * @param context
	 * @return value of MagicLink_Account
	 */
	public final administration.proxies.Account getMagicLink_Account(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		administration.proxies.Account result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.MagicLink_Account.toString());
		if (identifier != null)
			result = administration.proxies.Account.load(context, identifier);
		return result;
	}

	/**
	 * Set value of MagicLink_Account
	 * @param magiclink_account
	 */
	public final void setMagicLink_Account(administration.proxies.Account magiclink_account)
	{
		setMagicLink_Account(getContext(), magiclink_account);
	}

	/**
	 * Set value of MagicLink_Account
	 * @param context
	 * @param magiclink_account
	 */
	public final void setMagicLink_Account(com.mendix.systemwideinterfaces.core.IContext context, administration.proxies.Account magiclink_account)
	{
		if (magiclink_account == null)
			getMendixObject().setValue(context, MemberNames.MagicLink_Account.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.MagicLink_Account.toString(), magiclink_account.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return magicLinkMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final twofactorauth.proxies.MagicLink that = (twofactorauth.proxies.MagicLink) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "TwoFactorAuth.MagicLink";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
