// This file was generated by Mendix Modeler 6.10.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package twiliosms.proxies.constants;

import com.mendix.core.Core;

public class Constants
{
	// These are the constants for the TwilioSMS module

	public static java.lang.String getFromNumber()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("TwilioSMS.FromNumber");
	}

	public static java.lang.String getPassword()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("TwilioSMS.Password");
	}

	public static java.lang.String getSID()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("TwilioSMS.SID");
	}
}