// This file was generated by Mendix Modeler 6.10.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package twiliosms.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.MendixRuntimeException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class Microflows
{
	// These are the microflows for the TwilioSMS module
	public static twiliosms.proxies.SMSTest dS_SMSTest(IContext context)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			IMendixObject result = (IMendixObject)Core.execute(context, "TwilioSMS.DS_SMSTest", params);
			return result == null ? null : twiliosms.proxies.SMSTest.initialize(context, result);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void iVK_SendSMS(IContext context, twiliosms.proxies.SMSTest _sMSTest)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("SMSTest", _sMSTest == null ? null : _sMSTest.getMendixObject());
			Core.execute(context, "TwilioSMS.IVK_SendSMS", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static boolean sUB_SendSMS(IContext context, java.lang.String _to, java.lang.String _from, java.lang.String _body)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("To", _to);
			params.put("From", _from);
			params.put("Body", _body);
			return (java.lang.Boolean)Core.execute(context, "TwilioSMS.SUB_SendSMS", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
}