// This file was generated by Mendix Modeler 6.10.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package twofactorauth.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.MendixRuntimeException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class Microflows
{
	// These are the microflows for the TwoFactorAuth module
	public static boolean aSu_StartMagicLinkLoginHandler(IContext context)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			return (java.lang.Boolean)Core.execute(context, "TwoFactorAuth.ASu_StartMagicLinkLoginHandler", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static boolean aSu_StartTwoFactorLoginRequestHandlers(IContext context)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			return (java.lang.Boolean)Core.execute(context, "TwoFactorAuth.ASu_StartTwoFactorLoginRequestHandlers", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static boolean checkTFAActive(IContext context, java.lang.String _user)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("user", _user);
			return (java.lang.Boolean)Core.execute(context, "TwoFactorAuth.CheckTFAActive", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void resetTFAToken(IContext context, java.lang.String _user)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("user", _user);
			Core.execute(context, "TwoFactorAuth.ResetTFAToken", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static boolean sendTFAToken(IContext context, java.lang.String _user)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("user", _user);
			return (java.lang.Boolean)Core.execute(context, "TwoFactorAuth.SendTFAToken", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static boolean sUB_SendToken(IContext context, administration.proxies.Account _account)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("Account", _account == null ? null : _account.getMendixObject());
			return (java.lang.Boolean)Core.execute(context, "TwoFactorAuth.SUB_SendToken", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static administration.proxies.Account validateGUID(IContext context, java.lang.String _guid)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("guid", _guid);
			IMendixObject result = (IMendixObject)Core.execute(context, "TwoFactorAuth.ValidateGUID", params);
			return result == null ? null : administration.proxies.Account.initialize(context, result);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static boolean verifyTFAToken(IContext context, java.lang.String _user, java.lang.String _token)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("user", _user);
			params.put("token", _token);
			return (java.lang.Boolean)Core.execute(context, "TwoFactorAuth.VerifyTFAToken", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
}