// This file was generated by Mendix Modeler 6.10.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package twofactorauth.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.MendixRuntimeException;
import com.mendix.systemwideinterfaces.core.IContext;

public class Microflows
{
	// These are the microflows for the TwoFactorAuth module
	public static boolean checkTFAActive(IContext context, java.lang.String _user)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("user", _user);
			return (java.lang.Boolean)Core.execute(context, "TwoFactorAuth.CheckTFAActive", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void resetTFAToken(IContext context, java.lang.String _user)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("user", _user);
			Core.execute(context, "TwoFactorAuth.ResetTFAToken", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static boolean sendTFAToken(IContext context, java.lang.String _user)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("user", _user);
			return (java.lang.Boolean)Core.execute(context, "TwoFactorAuth.SendTFAToken", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static boolean startTwoFactorLoginRequestHandlers(IContext context)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			return (java.lang.Boolean)Core.execute(context, "TwoFactorAuth.StartTwoFactorLoginRequestHandlers", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static boolean verifyTFAToken(IContext context, java.lang.String _user, java.lang.String _token)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("user", _user);
			params.put("token", _token);
			return (java.lang.Boolean)Core.execute(context, "TwoFactorAuth.VerifyTFAToken", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
}